# =============================================================
#  NaturalShaders v4 — shaders.properties
# =============================================================

# Shadow: resolusi tinggi untuk detail pohon di god rays
shadowMapResolution=4096
shadowDistance=20.0
shadowIntervalSize=2.0
generateShadowMipmap=false
shadowHardwareFiltering0=false

# colortex0  scene color     RGBA8
# colortex1  lightmap UV     RG8
# colortex2  motion vectors  RG16F
# colortex3  normals         RGB8
# colortex4  TAA history     RGB16F  persistent!
# colortex5  bloom           RGB16F
# colortex6  glass mask      RGBA8

colortex4.format=RGB16F
colortex4.clear=false

colortex5.format=RGB16F
colortex5.clear=true

colortex6.format=RGBA8
colortex6.clear=true

composite.enabled=true
composite1.enabled=true
composite2.enabled=true
composite3.enabled=true

sliders=SHADOW_DARKNESS TORCH_BRIGHTNESS BLOOM_STRENGTH GODRAY_STRENGTH BIOME_FOG_DENSITY

screen=MAIN
screen.MAIN=SHADOW_DARKNESS TORCH_BRIGHTNESS BLOOM_STRENGTH GODRAY_STRENGTH <empty> [ATMOS]
screen.ATMOS=BIOME_FOG_DENSITY

option.SHADOW_DARKNESS=Shadow Min Light
value.SHADOW_DARKNESS=0.10 0.18 0.26 0.35 0.45
value.SHADOW_DARKNESS.default=0.26

option.TORCH_BRIGHTNESS=Torch Brightness
value.TORCH_BRIGHTNESS=1.0 1.5 2.0 2.5 3.0
value.TORCH_BRIGHTNESS.default=2.0

option.BLOOM_STRENGTH=Bloom Strength
value.BLOOM_STRENGTH=0.0 0.15 0.28 0.40
value.BLOOM_STRENGTH.default=0.28

option.GODRAY_STRENGTH=God Ray Strength
value.GODRAY_STRENGTH=0.0 0.20 0.35 0.55 0.75
value.GODRAY_STRENGTH.default=0.55

option.BIOME_FOG_DENSITY=Biome Fog Density
value.BIOME_FOG_DENSITY=0.0 0.5 1.0 1.5
value.BIOME_FOG_DENSITY.default=1.0

noiseTextureResolution=128
